# Generated by Django 4.2.20 on 2025-05-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartsalesapp', '0004_alter_product_status_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
